clubs/forms.py
import re

from django import forms
from django.conf import settings

from django.utils.translation import ugettext_lazy as _

from clublink.users.models import Address, User


class UserForm(forms.Form):
    first_name = forms.CharField(disabled=True)
    last_name = forms.CharField(disabled=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=False)
    password_confirm = forms.CharField(label=_('Confirm Password'), widget=forms.PasswordInput(),
                                       required=False)
    preferred_language = forms.ChoiceField(choices=settings.LANGUAGES)
    email = forms.EmailField(max_length=60)

    def __init__(self, user, *args, **kwargs):
        kw_initial = kwargs.get('initial', {})

        kwargs['initial'] = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'preferred_language': user.preferred_language,
            'email': user.email,
        }

        kwargs['initial'].update(kw_initial)

        super().__init__(*args, **kwargs)

    def clean_password(self):
        password = self.cleaned_data.get('password')

        if password:
            if len(password) < 8:
                raise forms.ValidationError(_('Password must be at least 8 characters.'))

            mixed_case = re.search(r'[A-Z]', password) and re.search(r'[a-z]', password)
            number = re.search(r'[0-9]', password)

            if not (mixed_case and number):
                raise forms.ValidationError(
                    _('Password must have at least one uppercase letter, one '
                      'lowercase letter and one number.'))

        return password

    def clean(self):
        data = self.cleaned_data
        password = data.get('password')
        password_confirm = data.get('password_confirm')

        if password and password != password_confirm:
            raise forms.ValidationError(_('Passwords do not match.'))

        return data


class ProfileForm(forms.Form):
    title = forms.CharField(max_length=10, required=False, disabled=True)
    dob = forms.DateField(required=False, disabled=True, label=_('Date of Birth'),
                          input_formats=['%d/%m/%Y'])
    employer = forms.CharField(max_length=80, required=False)
    position = forms.CharField(max_length=30, required=False)
    show_in_roster = forms.BooleanField(required=False, widget=forms.CheckboxInput())
    # show_phone = forms.ChoiceField(
    #     required=False,
    #     choices=(

    #     )
    #     )
    # show_email = forms.ChoiceField(
    #     required=False,
    #     choices=(

    #     )
    #     )


    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        kw_initial = kwargs.get('initial', {})

        self.user = user
        profile = user.profile

        addresses = user.addresses.all()

        phone_addresses = addresses.filter(phone__isnull=False)

        cell_addresses = addresses.filter(cell_phone__isnull=False)

        email_addresses = addresses.filter(email__isnull=False)

        ### SHOW PHONE ###
        self.fields['show_phone'] = forms.ChoiceField(
            choices=[
                (None, 'Do not show my phone')
            ],
            required=False,
            label=_('Phone number to show in roster')
            )

        if phone_addresses:
            self.fields['show_phone'].choices.extend(
                [(a.id, '{} ({})'.format(
                    a.phone, a.get__type_display()
                )) for a in phone_addresses]
            )
        else:
            self.fields['show_phone'].disabled = True
        ###

        ### SHOW CELL ###
        self.fields['show_cell'] = forms.ChoiceField(
            choices=[(None, 'Do not show my cell')],
            required=False,
            label=_('Cell number to show in roster'))

        if cell_addresses:
            self.fields['show_cell'].choices.extend(
                [(a.id, '{} ({})'.format(
                    a.cell_phone, a.get__type_display()
                ))
                 for a in cell_addresses])
        else:
            self.fields['show_cell'].disabled = True
        ###

        ### SHOW EMAIL ###
        self.fields['show_email'] = forms.ChoiceField(
            choices=[(None, 'Do not show my email')],
            required=False,
            label=_('Email to show in roster'))

        if email_addresses:
            self.fields['show_email'].choices.extend(
                [(a.id, '{} ({})'.format(
                    a.email, a.get__type_display()
                )) for a in email_addresses]
            )
        else:
            self.fields['show_email'].disabled = True
        ###

        kwargs['initial'] = {
            'show_email':
            profile.show_email.id if profile.show_email else None,
            'show_phone':
            profile.show_phone.id if profile.show_phone else None,
            'show_cell':
            profile.show_cell.id if profile.show_cell else None,
            'title':
            profile.title,
            'dob':
            profile.dob.strftime('%-d/%-m/%Y') if profile.dob else '',
            'employer':
            profile.employer,
            'position':
            profile.position,
            'show_in_roster':
            profile.show_in_roster if profile.show_in_roster else False,
        }

        kwargs['initial'].update(kw_initial)
        self.initial = kwargs['initial']


class AddressForm(forms.Form):
    COUNTRIES = (
        ('', ''),
        ('CAN', 'Canada'),
        ('USA', 'USA'),
    )

    REQUIRED_FIELDS = (
        'address1',
        'city',
        'country',
        'phone',
        'state',
        'postal_code',
    )

    address1 = forms.CharField(max_length=30, required=False, label=_('Address 1'))
    address2 = forms.CharField(max_length=30, required=False, label=_('Address 2'))
    city = forms.CharField(max_length=30, required=False)
    country = forms.ChoiceField(choices=COUNTRIES, required=False)
    cell_phone = forms.CharField(max_length=30, required=False)
    phone = forms.CharField(max_length=30, required=False)
    state = forms.CharField(max_length=3, required=False, label=_('Province/State'))
    postal_code = forms.CharField(max_length=10, required=False)

    def __init__(self, user, address_type, *args, **kwargs):
        kw_initial = kwargs.get('initial', {})

        try:
            address = user.addresses.get(type=address_type)
        except Address.DoesNotExist:
            pass
        else:
            kwargs['initial'] = {
                'address1': address.address1,
                'address2': address.address2,
                'city': address.city,
                'country': address.country,
                'cell_phone': address.cell_phone,
                'phone': address.phone,
                'state': address.state,
                'postal_code': address.postal_code
            }

            kwargs['initial'].update(kw_initial)

        super().__init__(*args, **kwargs)

        self.has_data = False
        for key in self.data:
            if key.startswith('{}-'.format(self.prefix)):
                data = self.data.get(key)
                self.has_data = self.has_data or bool(data)

        if self.has_data:
            for f in self.REQUIRED_FIELDS:
                self.fields[f].required = True


class SubscriptionsForm(forms.Form):
    email_dues_notice = forms.BooleanField(
        required=False, label=_('Receive annual dues notice via email'),
        widget=forms.CheckboxInput())
    email_statement = forms.BooleanField(
        required=False, label=_('Receive statement via email'), widget=forms.CheckboxInput())
    subscribe_score = forms.BooleanField(
        required=False, label=_('Score Golf Magazine'), widget=forms.CheckboxInput())
    subscribe_clublink_info = forms.BooleanField(
        required=False, label=_('ClubLink Life Weekly'), widget=forms.CheckboxInput())
    subscribe_club_info = forms.BooleanField(
        required=False, label=_('Club News'), widget=forms.CheckboxInput())

    def __init__(self, user, *args, **kwargs):
        kw_initial = kwargs.get('initial', {})

        profile = user.profile

        kwargs['initial'] = {
            'email_dues_notice': profile.email_dues_notice,
            'email_statement': profile.email_statement,
            'subscribe_score': profile.subscribe_score,
            'subscribe_clublink_info': profile.subscribe_clublink_info,
            'subscribe_club_info': profile.subscribe_club_info
        }

        kwargs['initial'].update(kw_initial)

        super().__init__(*args, **kwargs)


class PreferenceForm(forms.Form):
    mailing_address = forms.ChoiceField(
        required=True, label=_('Mailing Address'), choices=())
    billing_address = forms.ChoiceField(
        required=True, label=_('Billing Address'), choices=())

    def __init__(self, user, *args, **kwargs):
        self.user = user

        kw_initial = kwargs.get('initial', {})

        mailing_address = user.profile.mailing_address
        billing_address = user.profile.billing_address

        kwargs['initial'] = {
            'mailing_address': mailing_address.type if mailing_address else '',
            'billing_address': billing_address.type if billing_address else '',
        }

        kwargs['initial'].update(kw_initial)

        super().__init__(*args, **kwargs)

        addresses = [('', '')] + [(a.type, a.type) for a in user.addresses.all()]
        self.fields['mailing_address'].choices = addresses
        self.fields['billing_address'].choices = addresses

    def clean_mailing_address(self):
        address_type = self.cleaned_data.get('mailing_address')
        try:
            return Address.objects.get(user=self.user, type=address_type)
        except Address.DoesNotExist:
            raise forms.ValidationError(_('Invalid address.'))

    def clean_billing_address(self):

clubs/templates/clubs/my-account/annual-dues.jinja
{% extends 'clubs/my-account/base.jinja' %}

{% block main %}
    <div class="wrapper">
      <h2>{{ _('Annual Dues') }}</h2>
      {% if request.member.membership_number %}
        <iframe
            id="statement_iframe"
            src="//statements.clublinkprojects.ca/annual-dues/?member={{ request.member.encrypted_membership_number|quote_plus }}"
            height="100%"
            frameborder="0"
            width="100%"
        ></iframe>
        <script src="//hire.simplicant.com/iframeResizer.min.js"></script>
        <script>iFrameResize({log:true}, '#statement_iframe')</script>
      {% endif %}
    </div>
{% endblock %}

clubs/templates/clubs/my-account/base.jinja
{% extends 'clubs/generic/default.jinja' %}

clubs/templates/clubs/my-account/my-account.jinja
{% extends 'clubs/my-account/base.jinja' %}

{% block main %}
  <div class="wrapper">
    <h2>{{ _('Account Summary') }}</h2>

    <h4>{{ summary.get('name') }}</h4>

    <p class="centered">
      <strong class="summary-title inline">{{ _('Account number:') }}</strong>
      {{ summary.get('member_id') }}
    </p>

    <p class="centered">
      <strong class="summary-title inline">{{ _('Membership category:') }}</strong>
      {{ summary.get('category') }}
    </p>
  </div>

  <div class="inverted-bar" id="summary-balances">
    <div class="wrapper">
      <h2>{{ _('Current Balance') }}</h2>
      <div class="col-3 centered">
        <div>
          <div class="summary-title">{{ _('House') }}</div>
          <strong>${{ '{:,.2f}'.format(summary.get('house_balance', 0)) }}</strong>
        </div>
        <div>
          <div class="summary-title">{{ _('Annual Dues') }}</div>
          <strong>${{ '{:,.2f}'.format(summary.get('annual_dues_balance', 0)) }}</strong>
        </div>
        <div>
          <div class="summary-title">{{ _('Membership Fees') }}</div>
          <strong>${{ '{:,.2f}'.format(summary.get('membership_fee_balance', 0)) }}</strong>
        </div>
      </div>
    </div>
  </div>

  <div class="wrapper" id="summary-extra">
    <div class="col-2 centered">
      <div>
        <div class="summary-title">{{ _('Unspent Food & Beverage Minimum') }}</div>
        <strong>${{ '{:,.2f}'.format(summary.get('unspent_minimum_balance', 0)) }}</strong>
      </div>
      <div>
        <div class="summary-title">{{ _('Membership Fee Value Reward') }}</div>
        <strong>${{ '{:,.2f}'.format(summary.get('reward_balance', 0)) }}</strong>
      </div>
    </div>
  </div>

  {% if linked_members %}
    <div id="linked-members">
      <div class="wrapper">
        <div class="centered summary-title">
          <strong>{{ _('Linked Members') }}</strong>
        </div>

        <div class="col-3 centered linked-member-header">
          <div class="summary-title">{{ _('Account Name') }}</div>
          <div class="summary-title">{{ _('Account Number') }}</div>
          <div class="summary-title">{{ _('Membership Category') }}</div>
        </div>

        {% for member in linked_members %}
          <div class="col-3 centered linked-member">
            <div>{{ member.get('name') }}</div>
            <div>{{ member.get('member_id') }}</div>
            <div>{{ member.get('category') }}</div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}
{% endblock %}

clubs/templates/clubs/my-account/statement.jinja
{% extends 'clubs/my-account/base.jinja' %}

{% block main %}
    <div class="wrapper">
      <h2>{{ _('View Statement') }}</h2>

      {% if request.member.membership_number %}
        <iframe
            id="statement_iframe"
            src="{{ statement_url }}"
            scrolling="no"
            height="100%"
            frameborder="0"
            width="100%"
        ></iframe>
        <script src="//hire.simplicant.com/iframeResizer.min.js"></script>
        <script>iFrameResize({log:true}, '#statement_iframe')</script>
      {% endif %}

    </div>
{% endblock %}

clubs/templates/clubs/my-account/update-address.jinja
{% extends 'clubs/my-account/update-profile.jinja' %}

{% macro address_form(form) %}
  <div class="two-columns padded-top">
    {{ form_field(form.address1) }}
    {{ form_field(form.address2) }}
    {{ form_field(form.city) }}
    {{ form_field(form.country) }}
    {{ form_field(form.state) }}
    {{ form_field(form.postal_code) }}
    {{ form_field(form.phone) }}
    {{ form_field(form.cell_phone) }}
  </div>
{% endmacro %}

{% block main_form %}
  <div class="wrapper">
    {% for address_type in address_types %}
      <h4>{{ address_labels[address_type] }}</h4>
      {{ address_form(forms[address_type]) }}
    {% endfor %}
  </div>

  <div class="wrapper">
    <input type="submit" value="{{ _('Save') }}" />
  </div>
{% endblock %}

clubs/templates/clubs/my-account/update-profile.jinja
{% extends 'clubs/my-account/base.jinja' %}

{% from 'clubs/includes/macros.jinja' import checkbox, form_field %}

{% block body_class %}my-profile{% endblock %}

{% block main %}
  <form action="" method="post" novalidate class="update-profile">
    {{ csrf_input(csrf_token) }}

    <div class="wrapper">
      <h2>{{ _('My Profile') }}</h2>

    {% for message in messages %}
      <div class="message">{{ message }}</div>
    {% endfor %}

      <ul class="page-nav"><!--
        {% for item in submenu %}
          --><li class="{% if item[0] == request.path %}active{% endif %}">
            <a href="{{ item[0] }}" {% if item[2] %}target="_blank"{% endif %}>
              {{ item[1] }}
            </a>
          </li><!--
        {% endfor %}
      --></ul>
    </div>

    {% block main_form %}
      <div class="wrapper">
        <h4>{{ _('Update Profile') }}</h4>
        <div class="two-columns padded-top">
          {{ form_field(user_form.first_name) }}
          {{ form_field(user_form.last_name) }}

          {{ form_field(profile_form.title) }}
          {{ form_field(profile_form.dob) }}

          {{ form_field(user_form.email) }}
          {{ form_field(user_form.preferred_language) }}

          {{ form_field(profile_form.employer) }}
          {{ form_field(profile_form.position) }}

          {{ form_field(preference_form.mailing_address) }}
          {{ form_field(preference_form.billing_address) }}

          <div style="width: 100%; text-align: center;">
            <span style="display: inline-block;">
              {{ checkbox(profile_form.show_in_roster) }}
            </span>

            <span>
              {% if profile_form.show_in_roster.value() %}
                {% set phone_class = 'show-phone' %}
              {% else %}
               {% set phone_class = 'show-phone hidden' %}
              {% endif %}

               {{ form_field(profile_form.show_phone, phone_class) }}
            </span>

            <span>
              {% if profile_form.show_in_roster.value() %} {% set cell_class = 'show-cell' %} {% else %} {% set cell_class = 'show-cell hidden' %} {% endif %} {{ form_field(profile_form.show_cell, cell_class) }}
            </span>

            <span>
               {% if profile_form.show_in_roster.value() %} {% set email_class = 'show-email' %} {% else %} {% set email_class = 'show-email hidden' %} {% endif
              %}

              {{ form_field(profile_form.show_email, email_class) }}
            </span>
          </div>
        </div>
      </div>

      <hr />

      <div class="wrapper">
        <h4>{{ _('Change My Password') }}</h4>
        <p>{{ _('To leave your password unchanged simply leave these fields blank.') }}</p>
        <div class="two-columns margined">
          {{ form_field(user_form.password) }}
          {{ form_field(user_form.password_confirm) }}
        </div>
      </div>

      <div class="wrapper">
        <input type="submit" value="{{ _('Save') }}" />
      </div>
    {% endblock %}
  </form>

{% endblock %}

{% block extra_scripts %}

{{super()}}
  <script>
    $(document).ready(function () {
      $('#id_show_in_roster').on('change', function (e) {
        if ($(e.target).is(':checked')) {

          $('.show-email, .show-phone, .show-cell').removeClass('hidden').hide();
          $('.show-email, .show-phone, .show-cell').fadeIn();
        }
        else {
          $('.show-email, .show-phone, .show-cell').fadeOut();
        }
      })
    })
  </script>


{% endblock %}

clubs/templates/clubs/my-account/update-subscription.jinja
{% extends 'clubs/my-account/update-profile.jinja' %}

{% block main_form %}
  <div class="wrapper">
    <h4>{{ _('Communications') }}</h4>

    {{ checkbox(subscription_form.email_dues_notice) }}
    {{ checkbox(subscription_form.email_statement) }}
    {{ checkbox(subscription_form.subscribe_clublink_info) }}
    {{ checkbox(subscription_form.subscribe_club_info) }}
    {{ checkbox(subscription_form.subscribe_score) }}
  </div>

  <div class="wrapper">
    <input type="submit" value="{{ _('Save') }}" />
  </div>
{% endblock %}